apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-ts
  template:
    metadata:
      labels:
        app: worker-ts
    spec:
      containers:
      - name: worker-ts
        image: fabiomirandamonte/worker-ts:v1
        env:
        - name: API_URL
          value: "http://api-spring-service:8080/tarefas"

